FROM node:16

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json ./
COPY yarn.lock ./

RUN apt-get update
RUN apt-get install -y chromium
RUN yarn install --frozen-lockfile

# Bundle app source
COPY . .
CMD [ "yarn", "start" ]
