version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    command: nodemon start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    links:
      - redis
    environment:
      REDIS_CONNECTION_STRING_URL: redis://default@redis:6379
      APP_NAME: stock-api
      API_KEY: dummy
      NODE_ENV: development
      FINNHUB_TOKEN:
      FINANCIAL_MODELING_PREP_TOKEN:

  redis:
    image: redis
