FROM node:20

WORKDIR /usr/app

# Install app dependencies
COPY package.json ./
COPY yarn.lock ./

RUN apt-get update
RUN apt-get install -y chromium

RUN yarn global add nodemon
RUN yarn install --frozen-lockfile

COPY . .