FROM node:16

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json ./
COPY yarn.lock ./

RUN apt-get update

RUN yarn install

# Bundle app source
COPY . .

CMD [ "yarn", "start" ]